### ISSUE TITLE
App will not verify

### ISSUE THREAD

**Issue by FunkeDope** [Elcomsoft/eiftpi#1]
iPhone 11
iOS 16.1 (20B82)
Device in airplane mode, no wifi or mobile networking.

Flashed latest image to a Raspberry Pi 4

Installing the agent via EIFT works fine, however the agent app is unable to get the cert from the internet.

I can confirm the proxy is somewhat working as the only website that will load in Safari on the device is elcomsoft.com.

Agent just will not connect. Removing airplane mode and putting the device on WIFI or LTE successfully authenticates the agent.

**Comment by ESResearchDepartment** [comment]
I just tested verifying agent on iPhone 14 pro iOS 16.1 using RPI3, RPI4 and OrangePI5. All works fine.
Please test whether the issue still persists in v1.2

**Comment by FunkeDope** [comment]
I just tried again and it is now working with the newest image.
Thanks!
